config/routes.rb
Rails.application.routes.draw do
  root "imports#index"

  resources :imports do
    member do
      post :start_process
      post :remove_customers
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # relation was implemented to know to which import current customer related
  belongs_to :import

  validates_length_of :first_name, minimum: 2, allow_blank: false
  validates :email, email: { mode: :strict }, uniqueness: true
  validates :date_of_birth, presence: true
  validate :validate_age

  # search in customer table implemented by first_name, last_name and email fields
  scope :w_query, -> (q) { where('first_name ILIKE :q OR last_name ILIKE :q OR email ILIKE :q', q: "%#{q}%") if q.present? }

  def self.search(params)
    w_query(params[:query])
  end

  private
  # this custom validation should validate if Customer is older 18 and younger 100
  def validate_age
    if date_of_birth.present? && (date_of_birth > 18.years.ago.to_date || date_of_birth < 100.years.ago.to_date)
        errors.add(:date_of_birth, 'You should be over 18 years old.')
    end
  end
end

app/models/import.rb
class Import < ApplicationRecord
  mount_uploader :attachment, AttachmentUploader

  has_many :customers, dependent: :destroy

  validates :title, presence: true

  enum state: [:created, :started, :completed]

  scope :w_query, -> (q) { where(title: q) if q.present? }

  def self.search(params)
    w_query(params[:query])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/imports_controller.rb
class ImportsController < ApplicationController
  before_action :set_import, only: [:show, :edit, :update, :destroy, :remove_customers]

  def index
    @imports = Import.search(params).page params[:page]
  end

  def show
    # it was implemented to have possibility implement searching by customer table
    @customers = @import.customers.search(params)
  end

  def new
    @import = Import.new
  end

  def update
    @import.update(import_params)
    redirect_to root_path
  end

  def create
    import = Import.create!(import_params)
    redirect_to import_path(import)
  end

  def destroy
    @import.destroy!
    redirect_to root_path
  end

  def start_process
    ImportProcessingWorker.perform_async(params[:id])
  end

  # such actions should be moved to separate service
  def remove_customers
    @import.customers.destroy_all
    @import.update(state: :created, started_at: nil, completed_at: nil, invalid_customers: 0)
    redirect_to root_path
  end

  private

  def import_params
    params.require(:import).permit(:title, :attachment, :state)
  end

  def set_import
    @import = Import.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/imports/_customer_table.html.haml
- if @customers.any?
  .table-responsive
    %table.table.table-striped
      %tbody

  .input-group
    = form_tag(import_path(@import.id), method: "get", id: "search-form") do
      = text_field_tag :query, params[:search], placeholder: "Search Posts", class: 'form-control'
      %div.mt-2
        = submit_tag "Search", class: 'btn btn-primary'
  %h3.text-center
    Customers
  %table.table.table-striped.table-bordered.table-md{cellspacing: "0", width: "80%"}
    %thead
      %tr
        %th.th-sm
          First name
        %th.th-sm
          Last name
        %th.th-sm
          Email
        %th.th-sm
          Date of birth
    %tbody
      - customers.each do |item|
        %tr
          %td= item.first_name
          %td= item.last_name
          %td= item.email
          %td= item.date_of_birth.try(:strftime, '%d.%m.%Y %H:%M')
- else
  %h3.text-center We do not have any customers yet

app/views/imports/_form.html.haml
= simple_form_for @import, html: { class: 'inline-form' } do |f|
  %div
    .col-sm-6
      = f.input :title
    .col-sm-6.mt-4
      = f.input :attachment
    %br

    = f.button :submit, class: 'btn btn-primary'

app/views/imports/edit.html.haml
= render 'form'

app/views/imports/index.html.haml
%div.text-center
  = link_to 'Import file', new_import_path, class: "btn btn-primary btn-lg"

%br
%br
.input-group
  = form_tag(imports_path, method: "get", id: "search-form") do
    = text_field_tag :query, params[:search], placeholder: "Search Posts", class: 'form-control'
    %div.mt-2
      = submit_tag "Search", class: 'btn btn-primary'
%br

%table.table.table-striped.table-bordered.table-md{cellspacing: "0", width: "80%"}
  %thead
    %tr
      %th.th-sm
        Title
      %th.th-sm
        State
      %th.th-sm
        Started at
      %th.th-sm
        Completed at
      %th.th-sm
        File name
      %th.th-sm
        Created at
      %th.th-sm
        Actions
  %tbody
    - @imports.each do |item|
      %tr
        %td= item.title
        %td= item.state
        %td= item.started_at.try(:strftime, '%d.%m.%Y %H:%M')
        %td= item.completed_at.try(:strftime, '%d.%m.%Y %H:%M')
        %td= item.attachment.file&.filename
        %td= item.created_at.try(:strftime, '%d.%m.%Y %H:%M')
        %td
          .dropdown
            %button#dropdownMenuButton1.btn.btn-secondary.btn-sm.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", :typ => "button"}
              Options
            %ul.dropdown-menu{"aria-labelledby" => "dropdownMenuButton1"}
              %li= link_to 'Details', import_path(item), class: 'dropdown-item'
              %li= link_to 'Edit', edit_import_path(item), class: 'dropdown-item'
              %li= link_to 'Destroy', import_path(item), class: 'dropdown-item', method: :delete, remote: true, data: { confirm: "Are you sure?" }
    = paginate @imports

app/views/imports/new.html.haml
= render 'form'

app/views/imports/show.html.haml
%h1
  Import details
  = link_to 'Edit', edit_import_path(@import), class: 'btn btn-light'

.table-responsive
  %table.table.table-striped
    %tbody
      %tr
        %th ID
        %td= @import.id
      %tr
        %th Title
        %td= @import.title
      %tr
        %th State
        %td= @import.state
      %tr
        %th Created at
        %td= @import.created_at.try(:strftime, '%d.%m.%Y %H:%M')
      %tr
        %th Started at
        %td= @import.started_at.try(:strftime, '%d.%m.%Y %H:%M')
      %tr
        %th Completed at
        %td= @import.completed_at.try(:strftime, '%d.%m.%Y %H:%M')
      %tr
        %th Success customers
        %td= @import.customers.count
      %tr
        %th Failed customers
        %td= @import.invalid_customers

      - if @import.attachment.present?
        %tr
          - if @import.created?
            %th= link_to 'Start Import', start_process_import_path(@import), method: :post, class: 'btn btn-primary'
          - else
            %th= link_to 'Delete Import', remove_customers_import_path(@import), method: :post, class: 'btn btn-danger', data: { confirm: 'Are you sure?' }
          %td

= render 'customer_table', customers: @customers

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ImportPlatform
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    %link{:href => "https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css", :rel => "stylesheet"}/
    %script{:src => "https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"}
    %script{:crossorigin => "anonymous", :integrity => "sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT", :src => "https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js"}

  %body
    %nav.navbar.navbar-dark.bg-dark
      .container-fluid
        = link_to 'Import Platform', root_path, class: 'navbar-brand'
    %br
    %br
    .container
      = yield